# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.opam
          # An explicit key for restoring and saving the cache
          key: ${{ matrix.os }}-${{ matrix.ocaml-version }}-${{ hashFiles('*.opam') }}-build

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v1
        with:
          ocaml-version: 4.12.0
      
      - name: Install dependencies
        run: opam install . --deps-only --yes

      - name: Build release binaries
        run: opam exec -- make dist
      
      - name: Get node modules
        run: cd demo && yarn && yarn build
      
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          # Build directory to deploy
          build_dir: demo/dist
          # Allow Jekyll to build your site
          jekyll: false
          # Enable verbose output
          verbose: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
